[package]
name = "tlock"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_enum = "0.2.0"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive", "cargo"] }
crossterm = "0.27.0"
dirs = "5.0.1"
ini = "1.3.0"

